### ISSUE TITLE
incorrectly fails on.workflow_dispatch.inputs.*.options

### ISSUE THREAD

**Issue by airtonix** [mpalmer/action-validator#20]
```yaml
'on':
  workflow_dispatch:
    inputs:
      ApplicationName:
        description: 'Application name'
        required: true
        type: choice
        options: 
          - SomeName
          - SomeOtherName
          - YetMoarNames
```

results in : 

```shell
✖ action-validator:
Validation failed: ValidationState {
    errors: [
        OneOf {
            path: "/on",
            states: [
                ValidationState {
                    errors: [
                        Enum {
                            path: "/on",
                        },
                        WrongType {
                            path: "/on",
                            detail: "The value must be string",
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
                ValidationState {
                    errors: [
                        WrongType {
                            path: "/on",
                            detail: "The value must be array",
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
                ValidationState {
                    errors: [
                        Properties {
                            path: "/on/workflow_dispatch/inputs/ApplicationName",
                            detail: "Additional property 'options' is not allowed",
                        },
                        Properties {
                            path: "/on/workflow_dispatch/inputs/ApplicationName",
                            detail: "Additional property 'type' is not allowed",
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
            ],
        },
    ],
    missing: [],
    replacement: None,
}
```
