### ISSUE TITLE
Additional property "steps" not allowed on GitHub Action

### ISSUE THREAD

**Issue by sladesamuel** [mpalmer/action-validator#46]
I've setup a reusable GitHub Action that works when running on GitHub and [conforms to the GitHub documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runssteps), but fails validation through the use of this tool.

This is the action code:
```yaml
name: Install Terragrunt
description: Installs the specified Terragrunt version from the cache or internet

inputs:
  version:
    description: "The Terragrunt CLI version to install (expected format: v0.45.0)"
    required: true

runs:
  using: composite
  steps:
    - name: Cache Terragrunt
      uses: actions/cache@v3
      with:
        path: /bin/terragrunt
        key: ${{ runner.os }}-terragrunt-${{ inputs.version }}
        restore-keys: ${{ runner.os }}-terragrunt-${{ inputs.version }}

    - name: Setup Terragrunt ${{ inputs.version }}
      run: |
        sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/${{ inputs.version }}/terragrunt_linux_amd64"
        sudo chmod +x /bin/terragrunt
        terragrunt -v
```

And the validation error:
```
Treating .github/actions/install-terragrunt/action.yml as an Action definition
Validation failed: ValidationState {
    errors: [
        OneOf {
            path: "/runs",
            states: [
                ValidationState {
                    errors: [
                        Properties {
                            path: "/runs",
                            detail: "Additional property 'steps' is not allowed",
                        },
                        Const {
                            path: "/runs/using",
                        },
Fatal error validating .github/actions/install-terragrunt/action.yml: validation failed
                        Required {
                            path: "/runs/main",
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
                ValidationState {
                    errors: [
                        OneOf {
                            path: "/runs/steps/1",
                            states: [
                                ValidationState {
                                    errors: [
                                        Required {
                                            path: "/runs/steps/1/shell",
                                        },
                                    ],
                                    missing: [],
                                    replacement: None,
                                },
                                ValidationState {
                                    errors: [
                                        Required {
                                            path: "/runs/steps/1/uses",
                                        },
                                    ],
                                    missing: [],
                                    replacement: None,
                                },
                            ],
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
                ValidationState {
                    errors: [
                        Properties {
                            path: "/runs",
                            detail: "Additional property 'steps' is not allowed",
                        },
                        Const {
                            path: "/runs/using",
                        },
                        Required {
                            path: "/runs/image",
                        },
                    ],
                    missing: [],
                    replacement: None,
                },
            ],
        },
    ],
    missing: [],
    replacement: None,
}
```

From looking into the action validator code, it appears to be trying to match to an externally maintained schema. But this [schema appears to follow the GitHub documentation](https://github.com/SchemaStore/schemastore/blob/d3e6ab7727380b214acbab05570fb09a3e5d2dfc/src/schemas/json/github-action.json#L66), so I'm not sure why the tool is failing.

I initially tried using tool version `0.1.2` as mentioned through the examples. Using `0.5.1` made no difference to the error.

Any support/direction here would be appreciated. I'm only trialling this tool to see if it's sufficient for use within my projects, but this is a major blocker for me.
