### ISSUE TITLE
Request: expression single quote vs double quotes

### ISSUE THREAD

**Issue by jamesbraza** [mpalmer/action-validator#63]
https://docs.github.com/en/actions/learn-github-actions/expressions#literals talks about how double quotes aren't valid inside GitHub expressions:

```yaml
env:
    A1: ${{ "invalid" }}
    A2: ${{ 'valid' }}
```

I don't think [action-validator v0.5.3](https://github.com/mpalmer/action-validator/tree/v0.5.3) is catching this. I would like to request adding validation for that to this tool
