### ISSUE TITLE
failure to specify shell in action.yml doesn't get cause an error

### ISSUE THREAD

**Issue by till** [mpalmer/action-validator#68]
Heya! 👋🏼 

First off, thanks for creating this tool. :-) 

---

I think I found a bug, the following `action.yml` should trigger an error from your tool — but it does not (yet):

```yaml
name: 'foo/bar'
description: ''
branding:
  icon: 'zap'
  color: 'yellow'
runs:
  using: "composite"
  steps:
  - run: echo "Hello world"
```

Error on Github Actions is: `Required property is missing: shell`

The fix for it is:

```yaml
# ...
runs:
  using: "composite"
  steps:
  - run: echo "Hello world"
    shell: bash
```

Could be a problem with the json schema files? [I see "shell" there](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json#L78-L103), but not sure how that gets enforced.

So maybe the fix is there and they need to be updated. I am also not sure if you do anything "custom" on top of it, I have to admit I haven't checked.

Cheers!
